server:
  port: 12500

spring:
  application:
    name: littlemall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.56.10
    virtual-host: /
    username: guest
    password: guest